default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>

development:
  <<: *default
  database: debt_processor_development

test:
  <<: *default
  database: debt_processor_test

production:
  primary: &primary_production
    <<: *default
    database: debt_processor_production
  cache:
    <<: *primary_production
    database: debt_processor_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: debt_processor_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: debt_processor_production_cable
    migrations_paths: db/cable_migrate
